[package]
name = "copierd"
version = "0.1.0"
authors = ["jadex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5.0"
daemonize="0.4.1"
structopt = "0.3.13"
